[package]
name        = "bkg-kernel"
description = "BKG kernel: Genesis, RealmRouter"
version.workspace   = true
edition.workspace   = true
license.workspace   = true

[dependencies]
bkg-core.workspace = true
bkg-crypto.workspace = true
bkg-event.workspace = true
bkg-contracts.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
chrono.workspace = true
bkg-state={ path = "../state" }
bkg-enforce={ path = "../enforce" }
uuid.workspace=true
