use anyhow::Result;use clap::{Args,Subcommand};
use bkg_providers::{ProviderRegistry,ProviderToggleState};
use bkg_telemetry::{ModelTracker,QuotaMonitor};
use crate::{context::BkgContext,output::print_ok};
#[derive(Args)]pub struct ProvidersArgs{#[command(subcommand)]command:ProvidersCommand}
#[derive(Subcommand)]enum ProvidersCommand{List,Models{provider:String,#[arg(long)]all:bool},Toggle{provider:String},Refresh{provider:String},Telemetry{#[arg(long)]provider:Option<String>,#[arg(long)]model:Option<String>},Quota}
pub fn run(ctx:&BkgContext,args:ProvidersArgs)->Result<()>{match args.command{ProvidersCommand::List=>cmd_list(),ProvidersCommand::Models{provider,all}=>cmd_models(&provider,all),ProvidersCommand::Toggle{provider}=>cmd_toggle(ctx,&provider),ProvidersCommand::Refresh{provider}=>cmd_refresh(&provider),ProvidersCommand::Telemetry{provider,model}=>cmd_tel(ctx,provider.as_deref(),model.as_deref()),ProvidersCommand::Quota=>cmd_quota(ctx)}}
fn cmd_list()->Result<()>{let r=ProviderRegistry::default_populated();let rows:Vec<_>=r.summary().iter().map(|p|serde_json::json!({"id":p.id,"display_name":p.display_name,"tier":p.tier,"configured":p.configured,"toggle":p.toggle_mode.as_str(),"models_free":p.model_count_free,"models_all":p.model_count_all,"signup_url":p.signup_url})).collect();print_ok(serde_json::json!({"providers":rows,"count":rows.len()}))}
fn cmd_models(id:&str,all:bool)->Result<()>{let mut r=ProviderRegistry::default_populated();if all{r.toggle_provider(id);}let rows:Vec<_>=r.models_for(id).iter().map(|m|serde_json::json!({"id":m.id,"name":m.name,"free":m.is_free(),"reasoning":m.reasoning,"context_window":m.context_window})).collect();print_ok(serde_json::json!({"provider":id,"models":rows,"count":rows.len()}))}
fn cmd_toggle(ctx:&BkgContext,id:&str)->Result<()>{let path=ctx.data_dir.join("providers-toggle.json");let mut s=ProviderToggleState::load_from_file(&path);let mode=s.toggle_provider(id);s.save_to_file(&path).map_err(|e|anyhow::anyhow!("{e}"))?;print_ok(serde_json::json!({"provider":id,"mode":mode.as_str()}))}
fn cmd_refresh(id:&str)->Result<()>{let rt=tokio::runtime::Builder::new_current_thread().enable_all().build()?;rt.block_on(async{let mut r=ProviderRegistry::default_populated();if id=="all"{let res=r.refresh_all().await;let s:Vec<_>=res.iter().map(|(id,r)|match r{Ok(n)=>serde_json::json!({"provider":id,"models":n,"ok":true}),Err(e)=>serde_json::json!({"provider":id,"error":e.to_string(),"ok":false})}).collect();print_ok(serde_json::json!({"refreshed":s}))}else{match r.refresh(id).await{Ok(n)=>print_ok(serde_json::json!({"provider":id,"models":n,"ok":true})),Err(e)=>print_ok(serde_json::json!({"error":e.to_string(),"ok":false}))}}})}
fn cmd_tel(ctx:&BkgContext,p:Option<&str>,m:Option<&str>)->Result<()>{let t=ModelTracker::open(ctx.data_dir.join("telemetry.json")).unwrap_or_default();if let(Some(p),Some(m))=(p,m){return match t.stats_for(p,m){Some(s)=>print_ok(serde_json::json!({"provider":s.provider_id,"model":s.model_id,"calls":s.total_calls,"success_rate":s.success_rate(),"avg_latency_ms":s.avg_latency_ms()})),None=>print_ok(serde_json::json!({"note":"No telemetry yet."}))};}let rows:Vec<_>=t.all_stats().iter().map(|s|serde_json::json!({"provider":s.provider_id,"model":s.model_id,"calls":s.total_calls})).collect();print_ok(serde_json::json!({"models":rows,"cost_usd":t.total_cost_usd()}))}
fn cmd_quota(ctx:&BkgContext)->Result<()>{let m=QuotaMonitor::open(ctx.data_dir.join("quota.json")).unwrap_or_default();let rows:Vec<_>=m.all_states().iter().map(|s|serde_json::json!({"provider":s.provider_id,"requests_used":s.requests_used,"exhausted":s.is_exhausted()})).collect();print_ok(serde_json::json!({"quota":rows}))}
