[package]
name="bkg-render"
description="BKG bkg-render."
version.workspace=true
edition.workspace=true
license.workspace=true
[dependencies]
bkg-core.workspace=true
serde.workspace=true
serde_json.workspace=true
thiserror.workspace=true
chrono.workspace=true
uuid.workspace=true
bkg-compiler={ path = "../compiler" }
